//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.08 at 03:56:42 PM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://integration.gwclient.smallsystems.cma.se/")
package com.cosumer.client;
