//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.08 at 03:56:42 PM BDT 
//


package com.cosumer.client;

import lombok.ToString;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for send_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="send_t"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="message" type="{http://integration.gwclient.smallsystems.cma.se/}ParamsMtMsg"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "send_t", propOrder = {
    "message"
})
@XmlRootElement(name = "send")
@ToString
public class SendT {

    @XmlElement(required = true)
    protected ParamsMtMsg message;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link ParamsMtMsg }
     *     
     */
    public ParamsMtMsg getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamsMtMsg }
     *     
     */
    public void setMessage(ParamsMtMsg value) {
        this.message = value;
    }

}
