//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.08 at 03:56:42 PM BDT 
//


package com.cosumer.client;

import lombok.ToString;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for sendResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sendResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="data" type="{http://integration.gwclient.smallsystems.cma.se/}result_t"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendResponse", propOrder = {
    "data"
})
@XmlRootElement(name = "sendResponse")
@ToString
public class SendResponse {

    @XmlElement(required = true)
    protected ResultT data;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link ResultT }
     *     
     */
    public ResultT getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultT }
     *     
     */
    public void setData(ResultT value) {
        this.data = value;
    }

}
